sudo: false
language: node_js
node_js:
  - "10"
  - "12"
  - "14"

before_install:
  - travis_retry npm install

script:
  - npm test

notifications:
  email:
    - travis@nodejitsu.com
  irc: "irc.freenode.org#nodejitsu"
